MODIFIED products implementation
GFTprojecShoppingCart/GFTprojectShoppingCart pull request #11
Opened 2023-10-16 15:21 UTC by uapcent

Now it no longer requires a PRODUCTS database, it will make requests to the Warehouse endpoint

2023-10-16 15:36 UTC, joelvp approved these changes

2023-10-16 15:41 UTC, joelvp requested changes
Please merge previous PR in your local branch before PR a new one

2023-10-17 07:08 UTC, joelvp approved these changes

2023-10-17 07:11 UTC, mauisiri approved these changes

2023-10-17 07:12 UTC, Sergiolo01 approved these changes

2023-10-17 07:12 UTC, mauisiri approved these changes

2023-10-17 07:12 UTC, merged